steps:
  # build & push the container image
steps:
- name: gcr.io/$PROJECT_ID/awscli
  id: "Login to AWS / Docker"
  args: ["ecr-public", "get-login-password", "--region us-east-1"] #, "| docker", "login",  "username",  "$$KEY_ID", "password-stdin", "$$KEY"]
  env: ["AWS_ACCESS_KEY_ID=$$KEY_ID", "AWS_SECRET_ACCESS_KEY=$$KEY"]
  secretEnv: ['KEY_ID', 'KEY']
  #aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a3x7w5w4
#- name: gcr.io/$PROJECT_ID/awscli
#  id: "Build the Image"
#  args: ['ecr-public', 'get-login-password', '--region us-east-1', 'docker login --username $$KEY_ID --password-stdin $$KEY']
#  env: ["AWS_ACCESS_KEY_ID=$$KEY_ID", "AWS_SECRET_ACCESS_KEY=$$KEY"]
#  secretEnv: ['KEY_ID', 'KEY']


  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  id: "Deploy to Google Cloud"
  args: ['beta', 'run', 'deploy', 'e90-final', '--image', 'us-central1-docker.pkg.dev/ranciato-e90-final-project/e90-final/e90-final:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
availableSecrets:
  secretManager:
  - versionName: projects/279398674500/secrets/aws-key-id/versions/1
    env: 'KEY_ID'
  - versionName: projects/279398674500/secrets/aws-key/versions/1
    env: 'KEY'